"""create initial tables

Revision ID: 4f2d04563e9d
Revises: 
Create Date: 2026-08-18 17:38:42.765527+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '4f2d04563e9d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_models',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('model_type', sa.String(length=100), nullable=False),
    sa.Column('feature_names', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_models_name'), 'ml_models', ['name'], unique=False)
    op.create_table('baselines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('feature_name', sa.String(length=255), nullable=False),
    sa.Column('feature_type', sa.String(length=50), nullable=False),
    sa.Column('statistics', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('distribution', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baselines_model_id'), 'baselines', ['model_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('drift_results', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('overall_drift_score', sa.Float(), nullable=True),
    sa.Column('drifted_features', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_model_id'), 'runs', ['model_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('feature_name', sa.String(length=255), nullable=False),
    sa.Column('detector_type', sa.String(length=50), nullable=False),
    sa.Column('drift_score', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('notification_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_model_id'), 'alerts', ['model_id'], unique=False)
    op.create_index(op.f('ix_alerts_run_id'), 'alerts', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_run_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_model_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_runs_model_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_baselines_model_id'), table_name='baselines')
    op.drop_table('baselines')
    op.drop_index(op.f('ix_ml_models_name'), table_name='ml_models')
    op.drop_table('ml_models')
    # ### end Alembic commands ###